"""Graph provider contract used by the agent, GraphRAG, and case memory."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class GraphProvider(Protocol):
    name: str
    mock_mode: bool

    def get_transaction(self, txn_id: str) -> dict[str, Any] | None: ...
    def get_card(self, card_id: str) -> dict[str, Any] | None: ...
    def get_customer(self, customer_id: str) -> dict[str, Any] | None: ...
    def card_history(self, card_id: str, limit: int = 200) -> list[dict[str, Any]]: ...
    def customer_history(self, customer_id: str, limit: int = 400) -> list[dict[str, Any]]: ...
    def transaction_window(self, txn_id: str, hours: float = 24.0) -> list[dict[str, Any]]: ...
    def device_neighbors(self, device_id: str) -> dict[str, Any]: ...
    def region_neighbors(self, region: str) -> dict[str, Any]: ...
    def connected_cards(self, card_id: str) -> dict[str, Any]: ...
    def detect_card_testing(self, card_id: str, around_txn_id: str | None = None) -> dict[str, Any]: ...
    def detect_cnp(self, card_id: str, around_txn_id: str | None = None) -> dict[str, Any]: ...
    def detect_new_device_cnp(self, card_id: str, around_txn_id: str | None = None) -> dict[str, Any]: ...
    def detect_out_of_region(self, card_id: str, around_txn_id: str | None = None) -> dict[str, Any]: ...
    def detect_account_takeover(self, card_id: str, around_txn_id: str | None = None) -> dict[str, Any]: ...
    def detect_shared_origin(self, card_id: str, around_txn_id: str | None = None) -> dict[str, Any]: ...
    def related_closed_cases(
        self,
        card_id: str,
        customer_id: str,
        device_id: str | None = None,
        pattern: str | None = None,
    ) -> list[dict[str, Any]]: ...
    def search_closed_cases(self, query: str, pattern: str | None = None, limit: int = 5) -> list[dict[str, Any]]: ...
    def write_case(self, payload: dict[str, Any]) -> str: ...
    def known_ids(self) -> dict[str, set[str]]: ...
    def dataset_status(self) -> dict[str, Any]: ...
