"""Streamlit investigation UI — reads real cases/*.json. streamlit run app/ui.py"""
from __future__ import annotations

import json
from pathlib import Path

import streamlit as st

from app.config import ROOT, get_settings

st.set_page_config(page_title="FraudGraph", layout="wide", page_icon="◆")

CSS = """
<style>
.block-container { padding-top: 1.2rem; }
.fg-chip { display:inline-block; padding:2px 10px; border-radius:999px; font-size:0.8rem; margin-right:6px; }
.fg-fraud { background:#3b0d0d; color:#ffb4b4; }
.fg-legit { background:#0d2b16; color:#b6f3c8; }
.fg-unc { background:#2b240d; color:#ffe08a; }
.fg-auto { background:#0d2130; color:#9ad4ff; }
.fg-l1 { background:#2b1a0d; color:#ffd09a; }
.fg-l2 { background:#2b0d24; color:#f5b0e0; }
.fg-pending { border:1px solid #c9a227; padding:8px 12px; border-radius:8px; }
</style>
"""


def _cases_dir() -> Path:
    return get_settings().cases_dir


def _load_cases() -> list[Path]:
    d = _cases_dir()
    files = sorted(p for p in d.glob("HHG-*.json"))
    return files


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _report() -> dict | None:
    p = _cases_dir() / "benchmark_report.json"
    if p.exists():
        return json.loads(p.read_text(encoding="utf-8"))
    return None


def _chip(text: str, css: str) -> str:
    return f'<span class="fg-chip {css}">{text}</span>'


def main() -> None:
    st.markdown(CSS, unsafe_allow_html=True)
    files = _load_cases()
    report = _report()

    st.title("FraudGraph")
    st.caption("Agentic fraud investigation — TigerGraph HHGoa Task 4")

    if report and report.get("mock_mode"):
        st.warning(
            "Local / mock graph mode. `written_to_graph` is false unless a live TigerGraph write succeeded. "
            "These files were generated by the investigation pipeline; they are not claimed as hidden-key accuracy."
        )
        if report.get("limitations"):
            with st.expander("Dataset / backend limitations"):
                for line in report["limitations"]:
                    st.write("- " + line)

    if not files:
        st.info("No case files yet. Run `python -m app.run_benchmark` to generate `cases/HHG-*.json`.")
        return

    labels = [p.stem for p in files]
    selected = st.sidebar.selectbox("Case", labels)
    path = _cases_dir() / f"{selected}.json"
    data = _load_json(path)
    case = data["case"]
    sar = data["sar"]
    nba = data["next_best_actions"]

    verdict = case["verdict"]
    vcss = {"fraud": "fg-fraud", "legitimate": "fg-legit"}.get(verdict, "fg-unc")
    h1, h2, h3, h4 = st.columns(4)
    h1.metric("Case", data["case_id"])
    h2.metric("Status", case["status"])
    h3.markdown("**Verdict**<br>" + _chip(verdict, vcss), unsafe_allow_html=True)
    h4.metric("Fraud probability", f"{case['fraud_probability']:.2f}")

    st.markdown("---")
    left, right = st.columns((1.2, 1))

    with left:
        st.subheader("Evidence")
        for i, ev in enumerate(case.get("evidence") or [], start=1):
            with st.expander(f"{i}. {ev.get('claim', '')[:120]}"):
                st.write(ev.get("claim"))
                st.caption(f"source={ev.get('source')}  ref={ev.get('ref')}")
                ids = ev.get("entity_ids") or []
                if ids:
                    st.code(", ".join(ids))

        st.subheader("Investigation")
        st.write(f"**Pattern:** `{case.get('pattern')}`")
        if case.get("pattern") == "undocumented":
            st.write(case.get("pattern_description") or "")
        st.write(case.get("summary") or "")
        c1, c2 = st.columns(2)
        c1.write("**Affected transactions**")
        c1.code("\n".join(case.get("affected_txn_ids") or ["—"]))
        c2.write("**Connected cards**")
        c2.code("\n".join(case.get("connected_card_ids") or ["—"]))
        st.write("**Devices**")
        st.code("\n".join(case.get("connected_device_profiles") or ["—"]))
        st.metric("Exposure USD", f"{case.get('exposure_usd', 0):,.2f}")
        st.write("**Similar prior cases**")
        st.code(", ".join(case.get("similar_prior_cases") or ["—"]))
        st.caption(
            f"written_to_graph={case.get('written_to_graph')}  graph_case_id={case.get('graph_case_id') or '—'}"
        )

    with right:
        st.subheader("Next best actions")
        a, b = st.columns(2)
        with a:
            st.markdown("**Initial**")
            _render_actions(nba.get("initial") or [])
        with b:
            st.markdown("**Final**")
            _render_actions(nba.get("final") or [])
        st.info(nba.get("what_changed") or "nothing")

        pending = [x for x in (nba.get("final") or []) if x.get("route") in {"L1", "L2"}]
        if pending:
            st.markdown(
                '<div class="fg-pending"><b>Pending human approval</b><br>'
                + ", ".join(f"{p['action']} ({p['route']})" for p in pending)
                + "</div>",
                unsafe_allow_html=True,
            )

        st.subheader("SAR")
        if sar.get("file"):
            st.write(f"**Reason:** {sar.get('reason')}")
            st.write(sar.get("narrative"))
            st.write("**Subjects:** " + ", ".join(sar.get("subjects") or []))
            st.write(f"**Amount:** ${sar.get('total_amount_usd', 0):,.2f}")
            st.write("**Activity dates:** " + " → ".join(sar.get("activity_dates") or []))
        else:
            st.caption("No SAR filed. " + (sar.get("reason") or ""))

        st.subheader("Run metrics")
        m1, m2, m3 = st.columns(3)
        m1.metric("Tool calls", data.get("tool_calls", 0))
        m2.metric("Tokens", data.get("tokens", 0))
        m3.metric("Latency (s)", data.get("latency_s", 0))
        st.caption("Stop reason: " + (data.get("stop_reason") or ""))
        reqs = data.get("evidence_requests") or []
        if reqs:
            st.write("**Evidence requests**")
            for r in reqs:
                st.write(f"- `{r.get('type')}` after step {r.get('asked_after_step')}: {r.get('assumed_response')}")

    st.sidebar.markdown("---")
    st.sidebar.caption(f"Reading `{path.relative_to(ROOT) if path.is_relative_to(ROOT) else path}`")


def _render_actions(items: list[dict]) -> None:
    if not items:
        st.caption("—")
        return
    for item in items:
        route = item.get("route")
        css = {"auto": "fg-auto", "L1": "fg-l1", "L2": "fg-l2"}.get(route, "fg-auto")
        st.markdown(
            f"**{item.get('action')}** "
            + _chip(route, css)
            + f"<br/><small>{item.get('reason')}</small>",
            unsafe_allow_html=True,
        )


def _running_streamlit() -> bool:
    try:
        from streamlit.runtime.scriptrunner import get_script_run_ctx

        return get_script_run_ctx() is not None
    except Exception:
        return False


if __name__ == "__main__" or _running_streamlit():
    main()
